<%
'This function will change all of the BBCode
'into real smileys, also bold/italics/underline

Function BBCode(String)
	BBCode = Replace(String,":D","<img src='../../../images/emot/14.gif'  style='display:inline;' alt=':D'>")
	BBCode = Replace(BBCode,":]","<img src='../../../images/emot/1.gif'  style='display:inline;' alt=':]'>")
	BBCode = Replace(BBCode,":)","<img src='../../../images/emot/2.gif'  style='display:inline;' alt=':)'>")
    BBCode = Replace(BBCode,";)","<img src='../../../images/emot/5.gif'  style='display:inline;' alt=';)'>")
    BBCode = Replace(BBCode,":P","<img src='../../../images/emot/6.gif'  style='display:inline;' alt=':P'>")
	BBCode = Replace(BBCode,":(","<img src='../../../images/emot/3.gif'  style='display:inline;' alt=':('>")
	BBCode = Replace(BBCode,":[","<img src='../../../images/emot/12.gif'  style='display:inline;' alt=':['>")
	BBCode = Replace(BBCode,":S","<img src='../../../images/emot/11.gif'  style='display:inline;' alt=':S'>")
	BBCode = Replace(BBCode,"B)","<img src='../../../images/emot/13.gif'  style='display:inline;' alt='B)'>")
	BBCode = Replace(BBCode,"]:-(","<img src='../../../images/emot/7.gif'  style='display:inline;' alt=']:-('>")
	BBCode = Replace(BBCode,"]:-)","<img src='../../../images/emot/8.gif'  style='display:inline;' alt=']:-)'>")
	BBCode = Replace(BBCode,":O","<img src='../../../images/emot/9.gif'  style='display:inline;' alt=':O'>")
	
	BBCode = Replace(BBCode,":beer:","<img src='../../../images/emot/beer.gif'  style='display:inline;' alt=':beer:'>")
	BBCode = Replace(BBCode,":blackeye:","<img src='../../../images/emot/blackeye.gif'  style='display:inline;' alt=':blackeye:'>")
	BBCode = Replace(BBCode,":camp:","<img src='../../../images/emot/camp.gif'  style='display:inline;' alt=':camp:'>")
	BBCode = Replace(BBCode,":censored:","<img src='../../../images/emot/censored.gif'  style='display:inline;' alt=':censored:'>")
	BBCode = Replace(BBCode,":clap:","<img src='../../../images/emot/clap.gif'  style='display:inline;' alt=':clap:'>")
	BBCode = Replace(BBCode,":deer:","<img src='../../../images/emot/deer.gif'  style='display:inline;' alt=':deer:'>")
	BBCode = Replace(BBCode,":flower:","<img src='../../../images/emot/flower.gif'  style='display:inline;' alt=':flower:'>")
	BBCode = Replace(BBCode,":guns:","<img src='../../../images/emot/guns.gif'  style='display:inline;' alt=':guns:'>")
	BBCode = Replace(BBCode,":hellno:","<img src='../../../images/emot/hellno.gif'  style='display:inline;' alt=':hellno:'>")
	BBCode = Replace(BBCode,":help:","<img src='../../../images/emot/help.gif'  style='display:inline;' alt=':help:'>")
	BBCode = Replace(BBCode,":love:","<img src='../../../images/emot/love.gif'  style='display:inline;' alt=':love:'>")
	BBCode = Replace(BBCode,":out:","<img src='../../../images/emot/out.gif'  style='display:inline;' alt=':out:'>")
	BBCode = Replace(BBCode,":pray:","<img src='../../../images/emot/pray.gif'  style='display:inline;' alt=':pray:'>")
	BBCode = Replace(BBCode,":santa:","<img src='../../../images/emot/santa.gif'  style='display:inline;' alt=':santa:'>")
	BBCode = Replace(BBCode,":shh:","<img src='../../../images/emot/shh.gif'  style='display:inline;' alt=':shh:'>")
	BBCode = Replace(BBCode,":sleep:","<img src='../../../images/emot/sleep.gif'  style='display:inline;' alt=':sleep:'>")
	BBCode = Replace(BBCode,":stupid:","<img src='../../../images/emot/stupid.gif'  style='display:inline;' alt=':stupid:'>")
	BBCode = Replace(BBCode,":uzi:","<img src='../../../images/emot/uzi.gif'  style='display:inline;' alt=':uzi:'>")
	BBCode = Replace(BBCode,":whistle:","<img src='../../../images/emot/whistle.gif'  style='display:inline;' alt=':whistle:'>")
	BBCode = Replace(BBCode,":worthy:","<img src='../../../images/emot/worthy.gif'  style='display:inline;' alt=':worthy:'>")
	BBCode = Replace(BBCode,":monkey:","<img src='../../../images/emot/monkey.gif'  style='display:inline;' alt=':monkey:'>")
	BBCode = Replace(BBCode,":mouse:","<img src='../../../images/emot/mouse.gif'  style='display:inline;' alt=':mouse:'>")
	BBCode = Replace(BBCode,":olympics:","<img src='../../../images/emot/olympics.gif'  style='display:inline;' alt=':olympics:'>")
	BBCode = Replace(BBCode,":pig:","<img src='../../../images/emot/pig.gif'  style='display:inline;' alt=':pig:'>")
	BBCode = Replace(BBCode,":race:","<img src='../../../images/emot/race.gif'  style='display:inline;' alt=':race:'>")
	BBCode = Replace(BBCode,":shrug:","<img src='../../../images/emot/shrug.gif'  style='display:inline;' alt=':shrug:'>")
	BBCode = Replace(BBCode,":sly:","<img src='../../../images/emot/sly.gif'  style='display:inline;' alt=':sly:'>")
	BBCode = Replace(BBCode,":squirrel:","<img src='../../../images/emot/squirrel.gif'  style='display:inline;' alt=':squirrel:'>")
	BBCode = Replace(BBCode,"[b]","<b>")
	BBCode = Replace(BBCode,"[/b]","</b>")
	BBCode = Replace(BBCode,"[i]","<i>")
	BBCode = Replace(BBCode,"[/i]","</i>")
	BBCode = Replace(BBCode,"[u]","<u>")
	BBCode = Replace(BBCode,"[/u]","</u>")
End Function
%>