
Partial Class academico_PredictorDesercion_Default
    Inherits System.Web.UI.Page

    Sub demo()
        Dim body As String = "<div id=\':34p\' class=\'ii gt adP adO\'>"
        body = body + "<div id = \':35b\' class=\'a3s aXjCH m15d011830b4562e1\'>"
        body = body + "<div class=\'adM\'>"
        body = body + "</div>"
        body = body + "<div>"
        body = body + "<div class=\'adM\'>"
        body = body + "</div>"
        body = body + "<div style = \'font-family:&quot;Open Sans&quot;,sans-serif;width:75%;margin:0 auto\'>"
        body = body + "<div class=\'adM\'>"
        body = body + "</div>"
        body = body + "    <div>"
        body = body + "       <div class=\'adM\'>"
        body = body + "        </div>"
        body = body + "        <img src = \'http://i.imgur.com/3PJYBul.png\' width=\'200\' height=\'100\' style=\'margin:0 auto;display:block\' class=\'CToWUd a6T\' tabindex=\'0\'>"
        body = body + "        <div class=\'a6S\' dir=\'ltr\' style=\'opacity: 0.01; left: 468.5px; top: 66px;\'>"
        body = body + "           <div id = \':35p\' class=\'T-I J-J5-Ji aQv T-I-ax7 L3 a5q\' role=\'button\' tabindex=\'0\' aria-label=\'Descargar el archivo adjunto \' data-tooltip-class=\'a1V\' data-tooltip=\'Descargar\'>"
        body = body + "                <div class=\'aSK J-J5-Ji aYr\'>"
        body = body + "               </div>"
        body = body + "            </div>"
        body = body + "        </div></div>"
        body = body + "    <div style = \'color:black\'> Hola,"
        body = body + "        <span style = \'font -weight:700\'> Jose </span>"
        body = body + "    </div>"
        body = body + "   <table border=\'0\' width=\'100%\' cellpadding=\'0\' cellspacing=\'0\'>            "
        body = body + "        <tbody>"
        body = body + "            <tr>"
        body = body + "                <td style = \'background:none;border-bottom:1px solid #39cc98;height:1px;width:100%;margin:0px 0px 0px 0px\' > &nbsp;</td>"
        body = body + "            </tr>"
        body = body + "        </tbody>"
        body = body + "   </table>"
        body = body + "    <br>"
        body = body + "    <div style = \'font -weight:700;font-size:1.2em;color:black\' >¡Bienvenido a CARDMOVIL!</div>"
        body = body + "    <div style = \'margin -top:10px;line-height:180%;text-align:justify;color:black\'>"
        body = body + "       Confirma tu email para poder ingresar al Panel y empezar a usar CardMovil."
        body = body + "    </div>        "
        body = body + "    <div style = \'margin -top:10px;line-height:180%;text-align:justify;color:black\'>"
        body = body + "        Eso es todo por ahora."
        body = body + "    </div>"
        body = body + "    <div style=\'margin -top:15px;font-size:0.8em;line-height:180%;text-align:justify;color:gray\'> El enlace tiene una duración de dos días desde que se solicitó, en caso no se realice el cambio de contraseña este expirará.';"
        body = body + "    </div>"
        body = body + "    <div style = \'margin -top:20px;margin-bottom:20px\'>"
        body = body + "        <a href= \'http://integ-panel.cardmovil.com/#/activacion/LsY6ab-toJ7UwUsAvzbO0DSJv0T-F3MtdYuWBSxuQHAzgKDC288wQQKMR-k4yRatrNtI_P1Jr7sc5ZX_ggFc-Q==\' class=\'m_-4976141223608460281btn\' style=\'background-color:#39cc98;color:white;border-radius:5px;font-size:1em;padding:10px 10px;width:40%;text-decoration:none;font-weight:700;display:block;margin:0 auto;text-align:center\' target=\'_blank\' data-saferedirecturl=\'https://www.google.com/url?hl=es&amp;q=http://integ-panel.culqi.com/%23/activacion/LsY6ab-toJ7UwUsAvzbO0DSJv0T-F3MtdYuWBSxuQHAzgKDC288wQQKMR-k4yRatrNtI_P1Jr7sc5ZX_ggFc-Q%3D%3D&amp;source=gmail&amp;ust=1499048363807000&amp;usg=AFQjCNH-aIuBVDSOqcrJQmVLf5lY8HqiEA\'>Confirma tu email</a>"
        body = body + "    </div>  "
        body = body + "    <table border = \'0\' width=\'100%\' cellpadding=\'0\' cellspacing=\'0\'>"
        body = body + "        <tbody><tr>"
        body = body + "                <td style=\'background:none;border-bottom:1px solid #39cc98;height:1px;width:100%;margin:0px 0px 0px 0px\' > &nbsp;</td>"
        body = body + "             </tr>"
        body = body + "       </tbody>"
        body = body + "    </table><br>"
        body = body + "    <div style = \'font -size:0.9em;color:gray\' >"
        body = body + "        <div >"
        body = body + "            ¿Tienes dudas? Llámanos: (+01) 948 - 577334 o escríbenos a"
        body = body + "            <a href=\'mailto:softdonet@gmail.com\' style=\'color:#39cc98;text-decoration:none;font-weight:700\' target=\'_blank\'> soporte@cardmovil.com</a> ';           "
        body = body + "        </div> ';           "
        body = body + "         <div style = \'margin -top:5px\'>"
        body = body + "            © CardMovil - Todos los derechos reservados"
        body = body + "        </div>"
        body = body + "        <div class=\'yj6qo\'>"
        body = body + "         </div>"
        body = body + "        <div class=\'adL\'>"
        body = body + "        </div>"
        body = body + "    </div>"
        body = body + "    <div class=\'adL\'>"
        body = body + "    </div>"
        body = body + " </div>"
        body = body + "</div>"
        body = body + "<div class=\'adL\'>"
        body = body + "</div>"
        body = body + " </div>"
        body = body + "</div>"
    End Sub
End Class
