<% 
function cargacalendario()
	response.write("<script>")
	response.write("PopCalendar=getCalendarInstance();")
	response.write("PopCalendar.startAt = 0;")
	response.write("PopCalendar.showWeekNumber = 0;")
	response.write("PopCalendar.showToday = 1;") 
	response.write("PopCalendar.showWeekend = 1;")
	response.write("PopCalendar.showHolidays = 1;")
	response.write("PopCalendar.selectWeekend = 0;")
	response.write("PopCalendar.selectHoliday = 0;")
	response.write("PopCalendar.addCarnival = 1;")
	response.write("PopCalendar.addGoodFriday = 1;")
	response.write("PopCalendar.language = 0;")
	response.write("PopCalendar.defaultFormat ='mm-dd-yyyy';")
	response.write("PopCalendar.fixedX = -1;")
	response.write("PopCalendar.fixedY = -1;")
	response.write("PopCalendar.fade = 0.5;") 
	response.write("PopCalendar.shadow = 1;") 
	response.write("PopCalendar.move = 1;")
	response.write("PopCalendar.saveMovePos = 1;")
	response.write("PopCalendar.centuryLimit = 40;")
	response.write("PopCalendar.initCalendar();")
	response.write("</script>")
end function
%>