<html>

<head>
<meta http-equiv="Content-Language" content="es-pe">
<meta name="GENERATOR" content="Microsoft FrontPage 5.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>Escuela Profesional</title>
</head>

<body>

<table border="1" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="75%" id="AutoNumber1" height="35">
  <tr>
    <td width="27%" height="35"><font face="Arial">Escuela Profesional: </font>
    </td>
    <td width="73%" height="35"><font face="Arial"><select size="1" name="D1">
    <option selected>INGENIERIA DE SISTEMAS</option>
    <option>ADMINISTRACIÓN</option>
    <option>ECONOMÍA</option>
    <option>INGENIERÍA CIVIL</option>
    </select></font></td>
  </tr>
  <tr>
    <td width="27%" height="35"><font face="Arial">Fase de Tesis</font></td>
    <td width="73%" height="35">
    <form method="POST" action="--WEBBOT-SELF--">
      <!--webbot bot="SaveResults" U-File="\\srvbd\campusvirtual\_private\form_results.csv" S-Format="TEXT/CSV" S-Label-Fields="TRUE" --><p>
      <font face="Arial"><select size="1" name="D1">
      <option>TEMA DE INVESTIGACIÓN</option>
      <option>PROYECTO DE INVESTIGACIÓN</option>
      <option>EJECUCIÓN DE INVESTIGACIÓN</option>
      <option selected>INFORME DE INVESTIGACIÓN</option>
      </select><input type="submit" value="Consultar" name="B1"></font></p>
    </form>
    </td>
  </tr>
</table>
<table border="1" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="75%" id="AutoNumber2">
  <tr>
    <td width="28%"><b><font face="Arial">Tesista</font></b></td>
    <td width="29%" align="center"><b><font face="Arial">Proyecto</font></b></td>
    <td width="20%" align="center"><font face="Arial"><b>Asesor</b></font></td>
    <td width="35%" align="center"><font face="Arial"><b>Fecha Inicio</b></font></td>
    <td width="37%" align="center"><font face="Arial"><b>Fase</b></font></td>
  </tr>
  <tr>
    <td width="28%"><font face="Arial">Reyes Hernández Helen</font></td>
    <td width="29%" align="center">
    <p align="left"><font face="Arial">Propuesta de un modelo de BSC basado en 
    criterios de eficiencia, eficacia y efectividad</font></td>
    <td width="20%" align="center"><font face="Arial">Capuñay Uceda Oscar</font></td>
    <td width="35%" align="center"><font face="Arial">01/08/2006</font></td>
    <td width="37%" align="center"><font face="Arial">INFORME DE TESIS</font></td>
  </tr>
  <tr>
    <td width="28%">&nbsp;</td>
    <td width="29%" align="center">&nbsp;</td>
    <td width="20%" align="center">&nbsp;</td>
    <td width="35%" align="center">&nbsp;</td>
    <td width="37%" align="center">&nbsp;</td>
  </tr>
  <tr>
    <td width="28%">&nbsp;</td>
    <td width="29%" align="center">&nbsp;</td>
    <td width="20%" align="center">&nbsp;</td>
    <td width="35%" align="center">&nbsp;</td>
    <td width="37%" align="center">&nbsp;</td>
  </tr>
</table>

</body>

</html>
