<html>

<head>
<meta http-equiv="Content-Language" content="es-pe">
<meta name="GENERATOR" content="Microsoft FrontPage 5.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>Departamento académico</title>
</head>

<body>

<table border="1" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="58%" id="AutoNumber1" height="35">
  <tr>
    <td width="27%" height="35">Departamento académico: </td>
    <td width="73%" height="35">
    <form method="POST" action="--WEBBOT-SELF--">
      <!--webbot bot="SaveResults" U-File="\\srvbd\campusvirtual\_private\form_results.csv" S-Format="TEXT/CSV" S-Label-Fields="TRUE" --><p>
      <select size="1" name="D1">
      <option selected>DEPARTAMENTO DE INGENIERIA</option>
      <option>DEPARTAMENTO DE CIENCIAS EXACTAS</option>
      <option>DEPARTAMENTO DE HUMANIDADES</option>
      </select><input type="submit" value="Consultar" name="B1"></p>
    </form>
    </td>
  </tr>
</table>
<table border="1" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="59%" id="AutoNumber2">
  <tr>
    <td width="42%"><b><font face="Arial">Profesor</font></b></td>
    <td width="15%" align="center"><b><font face="Arial">Cant.Tesis Terminadas</font></b></td>
    <td width="15%" align="center"><b><font face="Arial">Cant. Tesis Proceso</font></b></td>
    <td width="43%" align="center"><b><font face="Arial">Total</font></b></td>
  </tr>
  <tr>
    <td width="42%"><font face="Arial">DAVILA HURTADO LUIS</font></td>
    <td width="15%" align="center"><font face="Arial">2</font></td>
    <td width="15%" align="center"><font face="Arial">3</font></td>
    <td width="43%" align="center"><font face="Arial">5</font></td>
  </tr>
  <tr>
    <td width="42%"><font face="Arial">OTAKE OYAMA LUIS</font></td>
    <td width="15%" align="center"><font face="Arial">3</font></td>
    <td width="15%" align="center"><font face="Arial">3</font></td>
    <td width="43%" align="center"><font face="Arial">6</font></td>
  </tr>
  <tr>
    <td width="42%"><font face="Arial">ZELADA VALDIVIESO HÉCTOR</font></td>
    <td width="15%" align="center"><font face="Arial">1</font></td>
    <td width="15%" align="center"><font face="Arial">2</font></td>
    <td width="43%" align="center"><font face="Arial">3</font></td>
  </tr>
</table>

</body>

</html>
